### PR TITLE
Limit scrolling to fix iOS glitching

### PR DESCRIPTION
**Pull request by Rob-ot**
This fix works around a bug in iOS Safari where when scrolling past the end of the scrollable area (a.k.a. "rubber banding" past the end) the screen erratically jumps around and looks awful.

To reproduce the bug:

1. Open the [sample page](http://devblog.orgsync.com/react-list/) on iOS Safari (does not reproduce on desktop for some reason)
2. Scroll the page down to the second from bottom example (the one with an initialIndex)
3. Scroll that example all the way to the bottom
4. Slowly scroll the example past the bottom to activate the rubber banding (you may have to scroll up slightly first so the rubber banding activates rather than scrolling the full page)
5. You should see some jarring and shaking of the screen.

I had to add two potentially expensive calls, `getViewportSize` and `getSpaceBefore` (with no cache!). 
Is there a way to use cached values for those?

Also, I wasn't sure what line 128 was doing, maybe there's a better name than `result`.

Thanks for making and maintaining this library!

### CODE REVIEW

**Comment by caseywebdev** [comment]
What device and version of iOS? I just tried this on my iPhone 5s iOS 9.2.1 and was not able to reproduce.

**Comment by Rob-ot** [comment]
We're seeing it on 9.2.1 on a iPhone 5 and a 6 Plus. Here's a video of the bug: https://www.dropbox.com/sc/xg7pwn6rhemy4wm/AAD3ht0dDMfetvS-yOxQfO8za

**Comment by caseywebdev** [comment]
Ah I see what you mean now. I merged this and used `scrollHeight/scrollWidth` instead of `getSpaceBefore`. It should yield the same value at a much lower cost. Please test `master` and confirm you cannot reproduce the bug, then I'll cut a patch release. Thanks!

**Comment by Rob-ot** [comment]
I tested the latest master and it's indeed fixed. Thanks so much!

**Comment by caseywebdev** [comment]
Released in `0.7.13`

**Pull request merged**
