### PR TITLE
Fix fast scroll issue on mobile device

### PR DESCRIPTION
**Pull request by ratson**
Pull request https://github.com/orgsync/react-list/pull/96 does not fix https://github.com/orgsync/react-list/issues/58 on mobile device browser, this is the fix for it.

### CODE REVIEW

**Comment by caseywebdev** [comment]
Can you produce an example where without this change scrolling is slow and with it, fast? I applied this patch locally and couldn't see a difference.

**Comment by ratson** [comment]
When I swipe down with fast acceleration, during the scrolling, quickly swipe back to the top, it will display blank page.
I tried it against a long list of [material-ui ListItem](http://www.material-ui.com/#/components/list).

**Comment by ratson** [comment]
@caseywebdev https://github.com/orgsync/react-list/blob/master/react-list.es6#L207 remove then add the update callback, would it be possible there is a race condition that the callback will be executed out of order, then causing rendering problem?

**Comment by caseywebdev** [comment]
I don't think so. Can you please replicate this? I'm not going to be able to find the problem until I can see it.

**Comment by ratson** [comment]
@caseywebdev  I am afraid that you have to test on Android Chrome to see the problem, with the instructions above.

The previous fix (https://github.com/orgsync/react-list/pull/96/files) looks really like a browser hack, and `mousewheel` won't work on touch devices.

**Comment by ratson** [comment]
I am closing this as it seems no one shares the same problem. I published [a fixed version](https://www.npmjs.com/package/react-list-fix) for my own use case, in case anyone want it.

**Pull request closed without merging**
